# Databricks App configuration for LakeStream CEP Builder
# Defines how the app is started when deployed to Databricks
# See: https://docs.databricks.com/en/dev-tools/databricks-apps/

name: lakestream-cep-builder
description: Visual Complex Event Processing Pipeline Builder for Databricks. Design streaming pipelines with 48 node types, generate Lakeflow SDP or Spark Structured Streaming code, and deploy to Lakeflow Jobs.

command:
  - sh
  - -c
  - ". .venv/bin/activate && cd backend && python3 startup.py 2>&1"

env:
  - name: ENVIRONMENT
    value: production

# Permissions required by the app
# - CAN_USE: Run the app
# - CAN_MANAGE: Deploy, update, delete
permissions:
  - level: CAN_USE
    group_name: users
