"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import Editor, { DiffEditor } from "@monaco-editor/react";
import type { Monaco } from "@monaco-editor/react";
import type { editor } from "monaco-editor";
import {
  Loader2,
  Check,
  AlertTriangle,
  AlertCircle,
  Pencil,
  ChevronDown,
  GitCompare,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { usePipelineStore } from "@/hooks/usePipelineStore";
import * as api from "@/lib/api";
import type { CodeAnnotation } from "@/lib/api";

interface CodePreviewProps {
  collapsed?: boolean;
  onToggleCollapse?: () => void;
  className?: string;
}

const PLACEHOLDER = "// Pipeline code will be generated here...";

export default function CodePreview({
  collapsed = false,
  onToggleCollapse,
  className,
}: CodePreviewProps) {
  const {
    generatedSdpCode,
    generatedSssCode,
    sdpAnnotations,
    sssAnnotations,
    setGeneratedCode,
    syncFromCode,
    selectNode,
    codeTarget,
    isGenerating,
    pipelineId,
  } = usePipelineStore();
  const [activeTab, setActiveTab] = useState<"sdp" | "sss">("sdp");
  const [isEditing, setIsEditing] = useState(false);
  const [diffMode, setDiffMode] = useState(false);
  const [lastDeployedCode, setLastDeployedCode] = useState<string | null>(null);
  const [diffLoading, setDiffLoading] = useState(false);
  const [syncStatus, setSyncStatus] = useState<"synced" | "warnings" | "parsing" | "error" | null>(null);
  const [syncMessage, setSyncMessage] = useState<string>("");
  const parseTimeoutRef = useRef<ReturnType<typeof setTimeout>>();
  const userEditedRef = useRef(false);

  const hasSdp = !!generatedSdpCode;
  const hasSss = !!generatedSssCode;
  const isHybrid = hasSdp && hasSss;

  useEffect(() => {
    if (activeTab === "sdp" && !hasSdp && hasSss) setActiveTab("sss");
    if (activeTab === "sss" && !hasSss && hasSdp) setActiveTab("sdp");
  }, [hasSdp, hasSss, activeTab]);

  const code = activeTab === "sdp" ? generatedSdpCode : generatedSssCode;
  const displayCode = code || PLACEHOLDER;
  const annotations = activeTab === "sdp" ? sdpAnnotations : sssAnnotations;

  const editorRef = useRef<editor.IStandaloneCodeEditor | null>(null);
  const monacoRef = useRef<Monaco | null>(null);
  const decorationsRef = useRef<string[]>([]);

  const applyDecorations = useCallback(
    (ed: editor.IStandaloneCodeEditor, anns: CodeAnnotation[]) => {
      if (!anns.length) {
        decorationsRef.current = ed.deltaDecorations(decorationsRef.current, []);
        return;
      }
      const monaco = monacoRef.current;
      if (!monaco) return;
      const newDecorations = anns.map((a) => ({
        range: new monaco.Range(a.start_line, 1, a.end_line, 1),
        options: {
          isWholeLine: true,
          glyphMarginClassName: "node-annotation-glyph",
          glyphMarginHoverMessage: { value: `Generated by: ${a.node_label}` },
          className: "node-annotation-line",
        },
      }));
      decorationsRef.current = ed.deltaDecorations(decorationsRef.current, newDecorations);
    },
    []
  );

  const handleEditorMount = useCallback(
    (ed: editor.IStandaloneCodeEditor, monaco: Monaco) => {
      editorRef.current = ed;
      monacoRef.current = monaco;
      applyDecorations(ed, annotations);
      ed.onDidChangeCursorPosition(() => {
        const pos = ed.getPosition();
        if (!pos) return;
        const ann = annotations.find((a) => pos.lineNumber >= a.start_line && pos.lineNumber <= a.end_line);
        if (ann) selectNode(ann.node_id);
      });
      ed.onMouseDown((e) => {
        if (e.target.type === monaco.editor.MouseTargetType.GUTTER_GLYPH_MARGIN && e.target.position) {
          const line = e.target.position.lineNumber;
          const ann = annotations.find((a) => line >= a.start_line && line <= a.end_line);
          if (ann) selectNode(ann.node_id);
        }
      });
    },
    [annotations, applyDecorations, selectNode]
  );

  useEffect(() => {
    const ed = editorRef.current;
    if (ed) applyDecorations(ed, annotations);
  }, [annotations, applyDecorations, activeTab]);

  const handleEditorChange = (value: string | undefined) => {
    userEditedRef.current = true;
    if (activeTab === "sdp") {
      setGeneratedCode(value ?? "", generatedSssCode);
    } else {
      setGeneratedCode(generatedSdpCode, value ?? "");
    }
  };

  // Debounced parse: when user edits SDP code, parse after 1s and sync to canvas
  useEffect(() => {
    if (!isEditing || activeTab !== "sdp" || !userEditedRef.current) return;
    const code = generatedSdpCode || "";
    if (!code.trim() || code === PLACEHOLDER) return;

    clearTimeout(parseTimeoutRef.current);
    parseTimeoutRef.current = setTimeout(async () => {
      setSyncStatus("parsing");
      try {
        const result = await api.parseCode(code);
        if (result.nodes.length > 0) {
          syncFromCode(result.nodes, result.edges);
          userEditedRef.current = false;
          if (result.warnings.length > 0) {
            setSyncStatus("warnings");
            setSyncMessage(result.warnings.join("; "));
          } else {
            setSyncStatus("synced");
            setSyncMessage("");
          }
        } else {
          setSyncStatus(null);
        }
      } catch {
        setSyncStatus("error");
        setSyncMessage("Parse failed");
      }
      setTimeout(() => setSyncStatus(null), 4000);
    }, 1000);
    return () => clearTimeout(parseTimeoutRef.current);
  }, [isEditing, activeTab, generatedSdpCode, syncFromCode]);

  // Fetch last deployed code when diff mode activates
  useEffect(() => {
    if (!diffMode || !pipelineId) {
      setLastDeployedCode(null);
      return;
    }
    let cancelled = false;
    setDiffLoading(true);
    api
      .getLatestDeploy(pipelineId, activeTab)
      .then((entry) => {
        if (!cancelled) {
          setLastDeployedCode(entry?.deployed_code ?? null);
        }
      })
      .finally(() => {
        if (!cancelled) setDiffLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [diffMode, pipelineId, activeTab]);

  const hasLastDeployed = lastDeployedCode !== null && lastDeployedCode !== undefined;
  const language = activeTab === "sdp" ? "sql" : "python";

  return (
    <div
      className={cn(
        "flex shrink-0 flex-col border-t border-slate-700 bg-slate-900/95",
        className
      )}
    >
      <div className="flex h-12 shrink-0 items-center justify-between border-b border-slate-700 px-4">
        <div className="flex items-center gap-2">
          {isGenerating && (
            <span className="flex items-center gap-1.5 text-sm text-slate-400">
              <Loader2 className="h-3.5 w-3.5 animate-spin" />
              Generating...
            </span>
          )}
          {codeTarget && !isGenerating && (
            <span className="rounded bg-slate-700 px-2 py-0.5 text-xs font-medium text-slate-300">
              {codeTarget.toUpperCase()}
            </span>
          )}
          {(isHybrid || hasSdp) && (
            <button
              onClick={() => setActiveTab("sdp")}
              className={cn(
                "rounded px-3 py-1.5 text-sm font-medium",
                activeTab === "sdp"
                  ? "bg-slate-700 text-slate-200"
                  : "text-slate-500 hover:text-slate-300"
              )}
              aria-label="SDP (SQL/Python) code tab"
              aria-pressed={activeTab === "sdp"}
            >
              SDP (SQL/Python)
            </button>
          )}
          {(isHybrid || hasSss) && (
            <button
              onClick={() => setActiveTab("sss")}
              className={cn(
                "rounded px-3 py-1.5 text-sm font-medium",
                activeTab === "sss"
                  ? "bg-slate-700 text-slate-200"
                  : "text-slate-500 hover:text-slate-300"
              )}
              aria-label="Structured Streaming (PySpark) code tab"
              aria-pressed={activeTab === "sss"}
            >
              Structured Streaming (PySpark)
            </button>
          )}
          {!hasSdp && !hasSss && !isGenerating && (
            <span className="text-sm text-slate-500">
              Add nodes to generate code
            </span>
          )}
          {syncStatus === "synced" && (
            <span className="flex items-center gap-1.5 text-xs text-emerald-400">
              <Check className="h-3.5 w-3.5" />
              Canvas synced from code
            </span>
          )}
          {syncStatus === "warnings" && (
            <span className="flex items-center gap-1.5 text-xs text-amber-400" title={syncMessage}>
              <AlertTriangle className="h-3.5 w-3.5" />
              Parse warnings: {syncMessage.slice(0, 50)}{syncMessage.length > 50 ? "…" : ""}
            </span>
          )}
          {syncStatus === "parsing" && (
            <span className="flex items-center gap-1.5 text-xs text-slate-400">
              <Loader2 className="h-3.5 w-3.5 animate-spin" />
              Parsing…
            </span>
          )}
          {syncStatus === "error" && (
            <span className="flex items-center gap-1.5 text-xs text-red-400">
              <AlertCircle className="h-3.5 w-3.5" />
              {syncMessage}
            </span>
          )}
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => setDiffMode(!diffMode)}
            aria-label={diffMode ? "Exit diff view" : "Compare with last deployed"}
            className={cn(
              "flex items-center gap-1.5 rounded px-2 py-1.5 text-sm",
              diffMode
                ? "bg-blue-600/20 text-blue-400"
                : "text-slate-400 hover:bg-slate-800 hover:text-slate-200"
            )}
            title={diffMode ? "Exit diff view" : "Compare with last deployed"}
          >
            <GitCompare className="h-3.5 w-3.5" />
            Diff
          </button>
          <button
            onClick={() => setIsEditing(!isEditing)}
            disabled={diffMode}
            aria-label={diffMode ? "Edit disabled in diff mode" : isEditing ? "Read-only mode" : "Edit mode"}
            className={cn(
              "flex items-center gap-1.5 rounded px-2 py-1.5 text-sm",
              diffMode && "opacity-50 cursor-not-allowed",
              isEditing
                ? "bg-blue-600/20 text-blue-400"
                : "text-slate-400 hover:bg-slate-800 hover:text-slate-200"
            )}
            title={diffMode ? "Edit disabled in diff mode" : isEditing ? "Read-only mode" : "Edit mode"}
          >
            <Pencil className="h-3.5 w-3.5" />
            {isEditing ? "Editing" : "Edit"}
          </button>
          <button
            onClick={onToggleCollapse}
            className="rounded p-1 text-slate-400 hover:bg-slate-800 hover:text-slate-200"
            title={collapsed ? "Expand" : "Collapse"}
            aria-label={collapsed ? "Expand code preview" : "Collapse code preview"}
          >
            <ChevronDown
              className={cn("h-4 w-4 transition-transform", collapsed && "rotate-180")}
            />
          </button>
        </div>
      </div>
      {!collapsed && (
        <div className="h-[180px] overflow-hidden" aria-label="Generated code editor">
          {diffMode ? (
            diffLoading ? (
              <div className="flex h-full items-center justify-center text-slate-400">
                <Loader2 className="h-6 w-6 animate-spin" />
                <span className="ml-2">Loading deploy history…</span>
              </div>
            ) : !pipelineId || !hasLastDeployed ? (
              <div className="flex h-full items-center justify-center text-slate-400">
                No previous deployment to compare against
              </div>
            ) : (
              <DiffEditor
                height="180px"
                original={lastDeployedCode ?? ""}
                modified={displayCode}
                language={language}
                theme="vs-dark"
                options={{
                  readOnly: true,
                  renderSideBySide: true,
                  minimap: { enabled: false },
                  fontSize: 12,
                }}
              />
            )
          ) : (
            <Editor
              height="180px"
              defaultLanguage={language}
              value={displayCode}
              theme="vs-dark"
              onMount={handleEditorMount}
              onChange={isEditing ? handleEditorChange : undefined}
              options={{
                readOnly: !isEditing,
                minimap: { enabled: false },
                fontSize: 12,
                glyphMargin: true,
              }}
            />
          )}
        </div>
      )}
    </div>
  );
}
