"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import Editor, { DiffEditor } from "@monaco-editor/react";
import type { Monaco } from "@monaco-editor/react";
import type { editor } from "monaco-editor";
import {
  Loader2,
  Check,
  AlertTriangle,
  AlertCircle,
  Pencil,
  ChevronDown,
  GitCompare,
  Sparkles,
  X,
} from "lucide-react";
import { useResizableReverse } from "@/hooks/useResizable";
import { cn } from "@/lib/utils";
import { usePipelineStore } from "@/hooks/usePipelineStore";
import * as api from "@/lib/api";
import type { CodeAnnotation } from "@/lib/api";

interface CodePreviewProps {
  collapsed?: boolean;
  onToggleCollapse?: () => void;
  onHeightChange?: (totalHeight: number) => void;
  className?: string;
}

const PLACEHOLDER = "// Pipeline code will be generated here...";

export default function CodePreview({
  collapsed = false,
  onToggleCollapse,
  onHeightChange,
  className,
}: CodePreviewProps) {
  const { size: editorHeight, onMouseDown: onResizeStart } = useResizableReverse({
    direction: "vertical",
    initialSize: 180,
    minSize: 100,
    maxSize: 500,
    storageKey: "lakestream-codedock-height",
  });
  const {
    generatedSdpCode,
    generatedSssCode,
    sdpAnnotations,
    sssAnnotations,
    setGeneratedCode,
    syncFromCode,
    selectNode,
    codeTarget,
    isGenerating,
    pipelineId,
  } = usePipelineStore();

  useEffect(() => {
    const totalHeight = collapsed ? 48 : 48 + editorHeight;
    onHeightChange?.(totalHeight);
  }, [editorHeight, collapsed, onHeightChange]);

  const [activeTab, setActiveTab] = useState<"sdp" | "sss">("sdp");
  const [isEditing, setIsEditing] = useState(false);
  const [diffMode, setDiffMode] = useState(false);
  const [lastDeployedCode, setLastDeployedCode] = useState<string | null>(null);
  const [diffLoading, setDiffLoading] = useState(false);
  const [explainOpen, setExplainOpen] = useState(false);
  const [explainLoading, setExplainLoading] = useState(false);
  const [explanation, setExplanation] = useState<string | null>(null);
  const [explainError, setExplainError] = useState<string | null>(null);
  const [syncStatus, setSyncStatus] = useState<"synced" | "warnings" | "parsing" | "error" | null>(null);
  const [syncMessage, setSyncMessage] = useState<string>("");
  const parseTimeoutRef = useRef<ReturnType<typeof setTimeout>>();
  const userEditedRef = useRef(false);

  const hasSdp = !!generatedSdpCode;
  const hasSss = !!generatedSssCode;
  const isHybrid = hasSdp && hasSss;

  useEffect(() => {
    if (activeTab === "sdp" && !hasSdp && hasSss) setActiveTab("sss");
    if (activeTab === "sss" && !hasSss && hasSdp) setActiveTab("sdp");
  }, [hasSdp, hasSss, activeTab]);

  const code = activeTab === "sdp" ? generatedSdpCode : generatedSssCode;
  const displayCode = code || PLACEHOLDER;
  const annotations = activeTab === "sdp" ? sdpAnnotations : sssAnnotations;

  const editorRef = useRef<editor.IStandaloneCodeEditor | null>(null);
  const monacoRef = useRef<Monaco | null>(null);
  const decorationsRef = useRef<string[]>([]);

  const applyDecorations = useCallback(
    (ed: editor.IStandaloneCodeEditor, anns: CodeAnnotation[]) => {
      if (!anns.length) {
        decorationsRef.current = ed.deltaDecorations(decorationsRef.current, []);
        return;
      }
      const monaco = monacoRef.current;
      if (!monaco) return;
      const newDecorations = anns.map((a) => ({
        range: new monaco.Range(a.start_line, 1, a.end_line, 1),
        options: {
          isWholeLine: true,
          glyphMarginClassName: "node-annotation-glyph",
          glyphMarginHoverMessage: { value: `Generated by: ${a.node_label}` },
          className: "node-annotation-line",
        },
      }));
      decorationsRef.current = ed.deltaDecorations(decorationsRef.current, newDecorations);
    },
    []
  );

  const handleEditorMount = useCallback(
    (ed: editor.IStandaloneCodeEditor, monaco: Monaco) => {
      editorRef.current = ed;
      monacoRef.current = monaco;
      applyDecorations(ed, annotations);
      ed.onDidChangeCursorPosition(() => {
        const pos = ed.getPosition();
        if (!pos) return;
        const ann = annotations.find((a) => pos.lineNumber >= a.start_line && pos.lineNumber <= a.end_line);
        if (ann) selectNode(ann.node_id);
      });
      ed.onMouseDown((e) => {
        if (e.target.type === monaco.editor.MouseTargetType.GUTTER_GLYPH_MARGIN && e.target.position) {
          const line = e.target.position.lineNumber;
          const ann = annotations.find((a) => line >= a.start_line && line <= a.end_line);
          if (ann) selectNode(ann.node_id);
        }
      });
    },
    [annotations, applyDecorations, selectNode]
  );

  useEffect(() => {
    const ed = editorRef.current;
    if (ed) applyDecorations(ed, annotations);
  }, [annotations, applyDecorations, activeTab]);

  const handleEditorChange = (value: string | undefined) => {
    userEditedRef.current = true;
    if (activeTab === "sdp") {
      setGeneratedCode(value ?? "", generatedSssCode);
    } else {
      setGeneratedCode(generatedSdpCode, value ?? "");
    }
  };

  // Debounced parse: when user edits SDP code, parse after 1s and sync to canvas
  useEffect(() => {
    if (!isEditing || activeTab !== "sdp" || !userEditedRef.current) return;
    const code = generatedSdpCode || "";
    if (!code.trim() || code === PLACEHOLDER) return;

    clearTimeout(parseTimeoutRef.current);
    parseTimeoutRef.current = setTimeout(async () => {
      setSyncStatus("parsing");
      try {
        const result = await api.parseCode(code);
        if (result.nodes.length > 0) {
          syncFromCode(result.nodes, result.edges);
          userEditedRef.current = false;
          if (result.warnings.length > 0) {
            setSyncStatus("warnings");
            setSyncMessage(result.warnings.join("; "));
          } else {
            setSyncStatus("synced");
            setSyncMessage("");
          }
        } else {
          setSyncStatus(null);
        }
      } catch {
        setSyncStatus("error");
        setSyncMessage("Parse failed");
      }
      setTimeout(() => setSyncStatus(null), 4000);
    }, 1000);
    return () => clearTimeout(parseTimeoutRef.current);
  }, [isEditing, activeTab, generatedSdpCode, syncFromCode]);

  // Fetch last deployed code when diff mode activates
  useEffect(() => {
    if (!diffMode || !pipelineId) {
      setLastDeployedCode(null);
      return;
    }
    let cancelled = false;
    setDiffLoading(true);
    api
      .getLatestDeploy(pipelineId, activeTab)
      .then((entry) => {
        if (!cancelled) {
          setLastDeployedCode(entry?.deployed_code ?? null);
        }
      })
      .finally(() => {
        if (!cancelled) setDiffLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [diffMode, pipelineId, activeTab]);

  const hasLastDeployed = lastDeployedCode !== null && lastDeployedCode !== undefined;
  const language = activeTab === "sdp" ? "sql" : "python";

  const handleExplain = async () => {
    const src = activeTab === "sdp" ? generatedSdpCode : generatedSssCode;
    if (!src || src.length < 20) return;
    setExplainOpen(true);
    setExplainLoading(true);
    setExplainError(null);
    setExplanation(null);
    try {
      const result = await api.aiExplainCode(src, activeTab);
      setExplanation(result.explanation);
    } catch (err: unknown) {
      const msg =
        err && typeof err === "object" && "userMessage" in err
          ? String((err as { userMessage?: string }).userMessage)
          : err instanceof Error ? err.message : "Failed to explain code";
      setExplainError(msg);
    } finally {
      setExplainLoading(false);
    }
  };

  return (
    <div
      className={cn(
        "fixed bottom-0 left-0 right-0 z-40 flex flex-col border-t border-[#30363d] bg-[#161b22]",
        className
      )}
    >
      <div className="flex h-12 shrink-0 items-center justify-between border-b border-[#30363d] px-4">
        <div className="flex items-center gap-2">
          {isGenerating && (
            <span className="flex items-center gap-1.5 text-sm text-[#8b949e]">
              <Loader2 className="h-3.5 w-3.5 animate-spin" />
              Generating...
            </span>
          )}
          {codeTarget && !isGenerating && (
            <span className="rounded bg-[#30363d] px-2 py-0.5 text-xs font-medium text-[#c9d1d9]">
              {codeTarget.toUpperCase()}
            </span>
          )}
          {(isHybrid || hasSdp) && (
            <button
              onClick={() => setActiveTab("sdp")}
              className={cn(
                "rounded px-3 py-1.5 text-sm font-medium",
                activeTab === "sdp"
                  ? "bg-[#30363d] text-[#e8eaed]"
                  : "text-[#6e7681] hover:text-[#c9d1d9]"
              )}
              aria-label="SDP (SQL/Python) code tab"
              aria-pressed={activeTab === "sdp"}
            >
              SDP (SQL/Python)
            </button>
          )}
          {(isHybrid || hasSss) && (
            <button
              onClick={() => setActiveTab("sss")}
              className={cn(
                "rounded px-3 py-1.5 text-sm font-medium",
                activeTab === "sss"
                  ? "bg-[#30363d] text-[#e8eaed]"
                  : "text-[#6e7681] hover:text-[#c9d1d9]"
              )}
              aria-label="Structured Streaming (PySpark) code tab"
              aria-pressed={activeTab === "sss"}
            >
              Structured Streaming (PySpark)
            </button>
          )}
          {!hasSdp && !hasSss && !isGenerating && (
            <span className="text-sm text-[#6e7681]">
              Add nodes to generate code
            </span>
          )}
          {syncStatus === "synced" && (
            <span className="flex items-center gap-1.5 text-xs text-emerald-400">
              <Check className="h-3.5 w-3.5" />
              Canvas synced from code
            </span>
          )}
          {syncStatus === "warnings" && (
            <span className="flex items-center gap-1.5 text-xs text-amber-400" title={syncMessage}>
              <AlertTriangle className="h-3.5 w-3.5" />
              Parse warnings: {syncMessage.slice(0, 50)}{syncMessage.length > 50 ? "…" : ""}
            </span>
          )}
          {syncStatus === "parsing" && (
            <span className="flex items-center gap-1.5 text-xs text-[#8b949e]">
              <Loader2 className="h-3.5 w-3.5 animate-spin" />
              Parsing…
            </span>
          )}
          {syncStatus === "error" && (
            <span className="flex items-center gap-1.5 text-xs text-red-400">
              <AlertCircle className="h-3.5 w-3.5" />
              {syncMessage}
            </span>
          )}
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={handleExplain}
            disabled={!code || code.length < 20}
            aria-label="Explain this code with AI"
            className={cn(
              "flex items-center gap-1.5 rounded px-2 py-1.5 text-sm",
              explainOpen
                ? "bg-purple-500/20 text-purple-400"
                : "text-[#8b949e] hover:bg-[#30363d] hover:text-[#e8eaed] disabled:opacity-40 disabled:cursor-not-allowed"
            )}
            title="Explain this code with AI"
          >
            <Sparkles className="h-3.5 w-3.5" />
            Explain
          </button>
          <button
            onClick={() => setDiffMode(!diffMode)}
            aria-label={diffMode ? "Exit diff view" : "Compare with last deployed"}
            className={cn(
              "flex items-center gap-1.5 rounded px-2 py-1.5 text-sm",
              diffMode
                ? "bg-[#1f6feb33] text-[#58a6ff]"
                : "text-[#8b949e] hover:bg-[#30363d] hover:text-[#e8eaed]"
            )}
            title={diffMode ? "Exit diff view" : "Compare with last deployed"}
          >
            <GitCompare className="h-3.5 w-3.5" />
            Diff
          </button>
          <button
            onClick={() => setIsEditing(!isEditing)}
            disabled={diffMode}
            aria-label={diffMode ? "Edit disabled in diff mode" : isEditing ? "Read-only mode" : "Edit mode"}
            className={cn(
              "flex items-center gap-1.5 rounded px-2 py-1.5 text-sm",
              diffMode && "opacity-50 cursor-not-allowed",
              isEditing
                ? "bg-[#1f6feb33] text-[#58a6ff]"
                : "text-[#8b949e] hover:bg-[#30363d] hover:text-[#e8eaed]"
            )}
            title={diffMode ? "Edit disabled in diff mode" : isEditing ? "Read-only mode" : "Edit mode"}
          >
            <Pencil className="h-3.5 w-3.5" />
            {isEditing ? "Editing" : "Edit"}
          </button>
          <button
            onClick={onToggleCollapse}
            className="rounded p-1 text-[#8b949e] hover:bg-[#30363d] hover:text-[#e8eaed]"
            title={collapsed ? "Expand" : "Collapse"}
            aria-label={collapsed ? "Expand code preview" : "Collapse code preview"}
          >
            <ChevronDown
              className={cn("h-4 w-4 transition-transform", collapsed && "rotate-180")}
            />
          </button>
        </div>
      </div>
      {!collapsed && (
        <div
          className="absolute left-0 right-0 top-0 z-10 h-1 cursor-row-resize hover:bg-[#1f6feb] active:bg-[#1f6feb] transition-colors"
          onMouseDown={onResizeStart}
          role="separator"
          aria-orientation="horizontal"
          aria-label="Resize code preview"
          title="Drag to resize"
        />
      )}
      {!collapsed && (
        <div className="overflow-hidden" style={{ height: editorHeight }} aria-label="Generated code editor">
          {diffMode ? (
            diffLoading ? (
              <div className="flex h-full items-center justify-center text-[#8b949e]">
                <Loader2 className="h-6 w-6 animate-spin" />
                <span className="ml-2">Loading deploy history…</span>
              </div>
            ) : !pipelineId || !hasLastDeployed ? (
              <div className="flex h-full items-center justify-center text-[#8b949e]">
                No previous deployment to compare against
              </div>
            ) : (
              <DiffEditor
                height={`${editorHeight}px`}
                original={lastDeployedCode ?? ""}
                modified={displayCode}
                language={language}
                theme="vs-dark"
                options={{
                  readOnly: true,
                  renderSideBySide: true,
                  minimap: { enabled: false },
                  fontSize: 12,
                }}
              />
            )
          ) : (
            <Editor
              height={`${editorHeight}px`}
              defaultLanguage={language}
              value={displayCode}
              theme="vs-dark"
              onMount={handleEditorMount}
              onChange={isEditing ? handleEditorChange : undefined}
              options={{
                readOnly: !isEditing,
                minimap: { enabled: false },
                fontSize: 12,
                glyphMargin: true,
              }}
            />
          )}
        </div>
      )}

      {explainOpen && (
        <div className="absolute bottom-full left-0 right-0 z-50 max-h-[300px] border-t border-purple-500/30 bg-[#0d1117] shadow-lg">
          <div className="flex items-center justify-between border-b border-[#30363d] px-4 py-2">
            <div className="flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-purple-400" />
              <span className="text-sm font-medium text-[#e8eaed]">Code Explanation</span>
              <span className="text-xs text-[#8b949e]">Powered by AI</span>
            </div>
            <button
              onClick={() => setExplainOpen(false)}
              className="rounded p-1 text-[#8b949e] hover:bg-[#30363d] hover:text-[#e8eaed]"
              aria-label="Close explanation"
            >
              <X className="h-4 w-4" />
            </button>
          </div>
          <div className="overflow-y-auto p-4" style={{ maxHeight: "250px" }}>
            {explainLoading && (
              <div className="flex items-center gap-2 text-sm text-[#8b949e]">
                <Loader2 className="h-4 w-4 animate-spin" />
                Analyzing code...
              </div>
            )}
            {explainError && <p className="text-sm text-red-400">{explainError}</p>}
            {explanation && (
              <div className="prose prose-invert prose-sm max-w-none text-sm text-[#c9d1d9] leading-relaxed whitespace-pre-wrap">
                {explanation}
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
